version: '3.3'
services:
    vsftpd:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "80:80"
            - "20-21:20-21"
            - "65500-65515:65500-65515"
